name: Generate Proto Code & Commit

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Download dependencies
        run: go mod download

      - name: Start services
        run: |
          docker compose up -d

      - name: Run tests
        env:
          KEYCLOAK_URL: http://keycloak:8080
          KEYCLOAK_REALM: omni
          KEYCLOAK_CLIENT_ID: omniauth-service
          KEYCLOAK_CLIENT_SECRET: omniauth-service-secret
        run: |
          go test -v ./...

      - name: Build service
        run: |
          go build -o omnauth ./src/main.go

      - name: Stop services
        if: always()
        run: |
          docker compose down

      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto: Refresh protobuf generated files in ./gen/"
          commit_options: '--no-verify'
          file_pattern: 'gen/'
          branch: ${{ github.ref_name }}
